In [1]:
!pip install quandl
!pip install PyPortfolioOpt==1.5.5
!pip install arch
!pip install numpy

Requirement already satisfied: quandl in /usr/local/lib/python3.11/dist-packages (3.7.0)
Requirement already satisfied: pandas>=0.14 in /usr/local/lib/python3.11/dist-packages (from quandl) (2.2.2)
Requirement already satisfied: numpy>=1.8 in /usr/local/lib/python3.11/dist-packages (from quandl) (1.26.4)
Requirement already satisfied: requests>=2.7.0 in /usr/local/lib/python3.11/dist-packages (from quandl) (2.32.3)
Requirement already satisfied: inflection>=0.3.1 in /usr/local/lib/python3.11/dist-packages (from quandl) (0.5.1)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.11/dist-packages (from quandl) (2.8.2)
Requirement already satisfied: six in /usr/local/lib/python3.11/dist-packages (from quandl) (1.17.0)
Requirement already satisfied: more-itertools in /usr/local/lib/python3.11/dist-packages (from quandl) (10.5.0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.14->quandl) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.14->quandl) (2024.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.7.0->quandl) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.7.0->quandl) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.7.0->quandl) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.7.0->quandl) (2024.12.14)
Requirement already satisfied: PyPortfolioOpt==1.5.5 in /usr/local/lib/python3.11/dist-packages (1.5.5)
Requirement already satisfied: cvxpy<2.0.0,>=1.1.19 in /usr/local/lib/python3.11/dist-packages (from PyPortfolioOpt==1.5.5) (1.6.0)
Requirement already satisfied: numpy<2.0.0,>=1.22.4 in /usr/local/lib/python3.11/dist-packages (from PyPortfolioOpt==1.5.5) (1.26.4)
Requirement already satisfied: pandas>=0.19 in /usr/local/lib/python3.11/dist-packages (from PyPortfolioOpt==1.5.5) (2.2.2)
Requirement already satisfied: scipy<2.0,>=1.3 in /usr/local/lib/python3.11/dist-packages (from PyPortfolioOpt==1.5.5) (1.13.1)
Requirement already satisfied: osqp>=0.6.2 in /usr/local/lib/python3.11/dist-packages (from cvxpy<2.0.0,>=1.1.19->PyPortfolioOpt==1.5.5) (0.6.7.post3)
Requirement already satisfied: clarabel>=0.5.0 in /usr/local/lib/python3.11/dist-packages (from cvxpy<2.0.0,>=1.1.19->PyPortfolioOpt==1.5.5) (0.9.0)
Requirement already satisfied: scs>=3.2.4.post1 in /usr/local/lib/python3.11/dist-packages (from cvxpy<2.0.0,>=1.1.19->PyPortfolioOpt==1.5.5) (3.2.7.post2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.19->PyPortfolioOpt==1.5.5) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.19->PyPortfolioOpt==1.5.5) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.19->PyPortfolioOpt==1.5.5) (2024.2)
Requirement already satisfied: qdldl in /usr/local/lib/python3.11/dist-packages (from osqp>=0.6.2->cvxpy<2.0.0,>=1.1.19->PyPortfolioOpt==1.5.5) (0.1.7.post5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas>=0.19->PyPortfolioOpt==1.5.5) (1.17.0)
Requirement already satisfied: arch in /usr/local/lib/python3.11/dist-packages (7.2.0)
Requirement already satisfied: numpy>=1.22.3 in /usr/local/lib/python3.11/dist-packages (from arch) (1.26.4)
Requirement already satisfied: scipy>=1.8 in /usr/local/lib/python3.11/dist-packages (from arch) (1.13.1)
Requirement already satisfied: pandas>=1.4 in /usr/local/lib/python3.11/dist-packages (from arch) (2.2.2)
Requirement already satisfied: statsmodels>=0.12 in /usr/local/lib/python3.11/dist-packages (from arch) (0.14.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.4->arch) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.4->arch) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.4->arch) (2024.2)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.11/dist-packages (from statsmodels>=0.12->arch) (1.0.1)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.11/dist-packages (from statsmodels>=0.12->arch) (24.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas>=1.4->arch) (1.17.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (1.26.4)

In [2]:
!pip install scikit-learn==1.2.2
import sklearn
import pypfopt
print(sklearn.__version__)
print(pypfopt.__version__)

Requirement already satisfied: scikit-learn==1.2.2 in /usr/local/lib/python3.11/dist-packages (1.2.2)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.11/dist-packages (from scikit-learn==1.2.2) (1.26.4)
Requirement already satisfied: scipy>=1.3.2 in /usr/local/lib/python3.11/dist-packages (from scikit-learn==1.2.2) (1.13.1)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from scikit-learn==1.2.2) (1.4.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn==1.2.2) (3.5.0)
1.2.2
1.5.5

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from datetime import datetime as dt
import datetime
import quandl
import math
from statsmodels.stats.diagnostic import het_arch
from arch import arch_model
from pypfopt import EfficientFrontier,objective_functions
from sklearn.decomposition import PCA
from sklearn.mixture import GaussianMixture
from sklearn.cluster import KMeans
from sklearn import metrics
from copy import deepcopy

In [4]:
!pip install yfinance==0.2.40
from pandas_datareader import data as pdr
import yfinance as yf
yf.pdr_override()

Requirement already satisfied: yfinance==0.2.40 in /usr/local/lib/python3.11/dist-packages (0.2.40)
Requirement already satisfied: pandas>=1.3.0 in /usr/local/lib/python3.11/dist-packages (from yfinance==0.2.40) (2.2.2)
Requirement already satisfied: numpy>=1.16.5 in /usr/local/lib/python3.11/dist-packages (from yfinance==0.2.40) (1.26.4)
Requirement already satisfied: requests>=2.31 in /usr/local/lib/python3.11/dist-packages (from yfinance==0.2.40) (2.32.3)
Requirement already satisfied: multitasking>=0.0.7 in /usr/local/lib/python3.11/dist-packages (from yfinance==0.2.40) (0.0.11)
Requirement already satisfied: lxml>=4.9.1 in /usr/local/lib/python3.11/dist-packages (from yfinance==0.2.40) (5.3.0)
Requirement already satisfied: platformdirs>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from yfinance==0.2.40) (4.3.6)
Requirement already satisfied: pytz>=2022.5 in /usr/local/lib/python3.11/dist-packages (from yfinance==0.2.40) (2024.2)
Requirement already satisfied: frozendict>=2.3.4 in /usr/local/lib/python3.11/dist-packages (from yfinance==0.2.40) (2.4.6)
Requirement already satisfied: peewee>=3.16.2 in /usr/local/lib/python3.11/dist-packages (from yfinance==0.2.40) (3.17.8)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /usr/local/lib/python3.11/dist-packages (from yfinance==0.2.40) (4.12.3)
Requirement already satisfied: html5lib>=1.1 in /usr/local/lib/python3.11/dist-packages (from yfinance==0.2.40) (1.1)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.11/dist-packages (from beautifulsoup4>=4.11.1->yfinance==0.2.40) (2.6)
Requirement already satisfied: six>=1.9 in /usr/local/lib/python3.11/dist-packages (from html5lib>=1.1->yfinance==0.2.40) (1.17.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.11/dist-packages (from html5lib>=1.1->yfinance==0.2.40) (0.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.3.0->yfinance==0.2.40) (2.8.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.3.0->yfinance==0.2.40) (2024.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.31->yfinance==0.2.40) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.31->yfinance==0.2.40) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.31->yfinance==0.2.40) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.31->yfinance==0.2.40) (2024.12.14)
yfinance: pandas_datareader support is deprecated & semi-broken so will be removed in a future verison. Just use yfinance.

In [5]:
def modify_date(date):
    return date[:10]

In [6]:
def data_cleaning(data):
    if (data.isna()).any().any():
        missing = np.where(data.isna())
        rows=missing[0]
        cols=missing[1]
        print(rows)
        for row in range(len(rows)):
            col=cols[row]
            if row == len(data)-1:
                data.iloc[row,col]=data.iloc[row-1,col]**2/data.iloc[row-2,col]
            elif row ==0:
                data.iloc[row,col]=data.iloc[row+1,col]**2/data.iloc[row+2,col]
            else:
                data.iloc[row,col]=math.sqrt(data.iloc[row-1,col]*data.iloc[row+1,col])
        print(data)

In [7]:
def get_price_years_ago(data, date,time):
    year_ago=date-datetime.timedelta(days=int(time*365))
    price_year_ago=data[data.index<=year_ago]
    return price_year_ago

In [8]:
def max_drawdown_absolute(returns):
    r = returns.add(1).cumprod()
    dd = r.div(r.cummax()).sub(1)
    mdd = dd.min()
    end = dd.argmin()
    start = r.iloc[:end].argmax()
    return abs(mdd), start, end

In [9]:
def fit_garch(data,p,q):
    lag = max(p,q)
    length =res.shape[0]
    am = arch_model(res, vol='Garch', p=1, o=0, q=1, dist='Normal')
    split_date = one_year_monthly_return.index.values[lag-1]
    results = am.fit(last_obs=split_date)
    forecasts = results.forecast(horizon=1, start = length-lag, method='simulation', simulations=1000)
    sims = forecasts.variance
    std = np.sqrt(np.sum(sims)*12/lag)
    return std

In [10]:
def post_allocation(dfMVOweight):

    dfMVOweight['equal']=1/len(dfMVOweight)
    numofstocks=len(dfMVOweight)
    allocationweight=allocation.loc[numofstocks,:]
    dfMVOweight['proportion']=''
    dfMVOweight['adjusted proportion']=''
    dfMVOweight['direct']=''
    residual=0
    for i in range(numofstocks):
        dfMVOweight.iloc[i,4]=dfMVOweight.iloc[i,1]/np.sum(dfMVOweight['PR_SR'])
        if (dfMVOweight.iloc[i,4]+residual/(numofstocks-i))>allocationweight[0]:
            dfMVOweight.iloc[i,5]=allocationweight[0]
        else:
            dfMVOweight.iloc[i,5]=(dfMVOweight.iloc[i,4]+residual/(numofstocks-i))
        residual+=dfMVOweight.iloc[i,4]-dfMVOweight.iloc[i,5]
    for i in range(int(allocationweight[1])):
        dfMVOweight.iloc[i,6]=allocationweight[0]
    for i in range(int(allocationweight[1]),int(allocationweight[1]+allocationweight[3])):
        dfMVOweight.iloc[i,6]=allocationweight[2]
    return dfMVOweight

In [11]:
def output(weight):
    if stock_type == "S&P100":
      OEX=pdr.get_data_yahoo("^OEX", start=start_swan_date, end=end_swan_date)["Adj Close"]

    elif stock_type == "S&P500":
      OEX=pdr.get_data_yahoo("SPY", start=start_swan_date, end=end_swan_date)["Adj Close"]

    stock_price=pdr.get_data_yahoo(list(weight.index), start=start_swan_date, end=end_swan_date)["Adj Close"]
    OEX.to_csv("oex.csv")
    injected_result = pd.DataFrame(index = stock_price.index )
    S1=np.array(10000*weight.T)/np.array(stock_price.iloc[0,:]).T
    portfolio_value = stock_price@S1.T
    injected_result["portfolio_value"]=portfolio_value
    S2 = 10000/float(OEX[0])
    injected_result["oex"]=S2*OEX
    return injected_result

# Step 1 - Preselection

In [12]:
# Preselection parameters set up
method = "K_means_multiple"          # or avg or anyother method
stock_type = "S&P500"
end_swan = "Swan9"         #equals the last swan before the swan we are going to predict
start_swan="Swan5"
start = dt(2020,11,1)
end = dt(2022,1,3)
selected_stock_number = 19     #number of stock preselected
start_swan_date = dt(2022,1,3)
end_swan_date = dt(2023,1,1)
w1 = 0.1
w2 = 0.1
MA_days = 30
N = 17 # This parameter is set to help classification method like K-means

In [25]:
#read all stocks and their swan beta
if stock_type == "S&P100":
    portfolio_beta = pd.read_excel("All_SwanBeta100.xlsx",index_col=0)
else:
    portfolio_beta = pd.read_excel("/content/BetaMartix S&P500 Dennis 2024.xlsx",index_col=0)

In [26]:
selected_swans_var=portfolio_beta.loc[:,start_swan:end_swan]
portfolio_beta =portfolio_beta[ selected_swans_var.T.isnull().sum()<selected_swans_var.shape[1]-1]

In [27]:
portfolio_beta= portfolio_beta.loc[:,"Swan1":end_swan]
portfolio_beta

,Swan1,Swan2,Swan3,Swan4,Swan5,Swan6,Swan7,Swan8,Swan9
Ticker,,,,,,,,,
A,NaN,NaN,NaN,2.129657,1.408493,2.084547,1.194656,0.682441,0.763786
AAL,NaN,NaN,NaN,NaN,1.607495,1.783416,0.613406,1.207817,1.892777
AAPL,0.803017,1.957671,0.810491,1.374259,0.838225,0.265718,1.771183,1.901494,0.909584
ABBV,NaN,NaN,NaN,NaN,NaN,NaN,1.196566,0.593982,0.933795
ABC,NaN,NaN,1.799041,-0.098415,0.500850,0.644569,1.249513,1.141485,0.660946
...,...,...,...,...,...,...,...,...,...
YUM,NaN,NaN,-0.250673,-0.054483,0.745233,0.626758,1.146095,0.138012,1.372255
ZBH,NaN,NaN,NaN,-0.296565,1.240598,1.076392,0.777202,1.295412,1.468092
ZBRA,NaN,NaN,1.096156,0.459355,1.041248,1.660871,2.720121,0.815003,0.860525
ZION,0.551030,0.472413,1.732495,1.121834,1.954552,2.324819,1.097932,1.234350,1.406848
ZTS,NaN,NaN,NaN,NaN,NaN,NaN,1.087978,0.787473,1.058199

In [24]:
corr=portfolio_beta.corr()
selected_corr=corr.loc["Swan1":end_swan,"Swan1":end_swan]
corr1={}
for i in range(selected_corr.shape[1]):
    for j in range(i+1,selected_corr.shape[0]):
        selected_corr.iloc[j,i]=np.nan

In [ ]:
selected_corr

,Swan1,Swan2,Swan3,Swan4,Swan5,Swan6,Swan7,Swan8,Swan9
Swan1,1.0,0.234634,0.200861,0.080872,-0.010629,0.155286,0.054266,0.227031,0.106071
Swan2,NaN,1.000000,0.372235,0.212392,0.260321,0.243822,-0.010243,0.216744,0.003824
Swan3,NaN,NaN,1.000000,0.100094,0.160429,0.324700,0.226882,0.353315,0.092120
Swan4,NaN,NaN,NaN,1.000000,0.033906,0.174311,0.079488,0.150590,0.005533
Swan5,NaN,NaN,NaN,NaN,1.000000,0.493237,0.167631,0.275134,0.443963
Swan6,NaN,NaN,NaN,NaN,NaN,1.000000,0.272880,0.504682,0.389450
Swan7,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,0.250702,0.153897
Swan8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,0.299758
Swan9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000

In [ ]:
avg=selected_corr.mean(axis=1)
weight_swan = avg/sum(avg)
selected_beata=portfolio_beta.loc[:,start_swan:end_swan].fillna(0)
#portfolio_beta["corr_beta"]=selected_beata@weight_swan
#portfolio_beta=portfolio_beta.sort_values(by=["corr_beta"])

In [ ]:
portfolio_beta

,Swan-4,Swan-3,Swan-2,Swan-1,Swan1,Swan2,Swan3,Swan4,Swan5,Swan6,Swan7,Swan8,Swan9,Swan10a,Swan10b
stickers,,,,,,,,,,,,,,,
A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.129658,1.408494,2.084543,1.194656,0.682441,0.763786,1.349095,1.349100
AAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.607496,1.783414,0.613406,1.207817,1.892777,2.172210,2.172218
AAP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.525701,0.207075,-0.048495,-0.125923,0.578707,1.299581,1.188325,1.188330
AAPL,NaN,NaN,1.977230,-0.37653,0.803019,1.957667,0.810489,1.374260,0.838224,0.265716,1.771181,1.901494,0.909584,1.040690,1.040694
ABBV,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.196568,0.593981,0.933795,-0.760908,-0.760912
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
YUM,NaN,NaN,NaN,NaN,NaN,NaN,-0.250675,-0.054484,0.745234,0.626755,1.146096,0.138012,1.372254,1.181589,1.181593
ZBH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.296564,1.240597,1.076391,0.777204,1.295413,1.468093,0.596361,0.596363
ZBRA,NaN,NaN,NaN,NaN,NaN,NaN,1.096154,0.459356,1.041249,1.660868,2.720119,0.815003,0.860525,2.662073,2.662082
ZION,NaN,NaN,0.324334,1.38323,0.551030,0.472412,1.732492,1.121835,1.954552,2.324816,1.097931,1.234350,1.406848,0.177742,0.177743
ZTS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.087976,0.787475,1.058199,1.738626,1.738633

In [ ]:
if method == "gamma":
    portfolio_beta["avg"]=portfolio_beta.loc[:,start_swan:end_swan].mean(axis=1)
    portfolio_beta["avg_sd"]=portfolio_beta.loc[:,start_swan:end_swan].mean(axis=1)+portfolio_beta.loc[:,start_swan:end_swan].std(axis=1,ddof=0)
    portfolio_beta=portfolio_beta.sort_values(by=["avg_sd"])
    preselected_stock = portfolio_beta.iloc[:selected_stock_number,:]
elif method =="average":
    portfolio_beta["avg"]=portfolio_beta.loc[:,start_swan:end_swan].mean(axis=1)
    #Select 18 stocks
    portfolio_beta=portfolio_beta.sort_values(by=["avg"])
    preselected_stock = portfolio_beta.iloc[:selected_stock_number,:]

elif method == "K_means":
    selected_beta =portfolio_beta.loc[:,start_swan:end_swan].dropna()
    Y_predic = selected_beta[end_swan].copy()
    Kmean = KMeans(n_clusters=N,random_state=1)#set the random_state to keep modeling the same every run
    Kmean.fit(selected_beta)
    ct = Kmean.cluster_centers_
    labels = Kmean.labels_
    current_dbscore=metrics.davies_bouldin_score(selected_beta, labels)
    print(current_dbscore)
    selected_beta["Group"]=Kmean.labels_
    print(selected_beta['Group'])
    res = ct.mean(axis=1)
    res [res<0]=0

    min_group = np.where(res==min(res))
    for i in range(N):
        Y_predic[selected_beta["Group"] == i] = res [i]
    selected_beta ["avg"]=Y_predic.values
    selected_beta=selected_beta.sort_values(by=["avg"])
    first_group=selected_beta[selected_beta["Group"]==selected_beta["Group"][0]]
    if first_group.shape[0] <10:
        second_group = selected_beta[selected_beta["Group"]==selected_beta["Group"][first_group.shape[0]]]
        preselected_stock = pd.concat([first_group,second_group],axis=0,ignore_index=False)
    else:
        preselected_stock = first_group

# Use results from multiple clusters
elif method=="K_means_multiple":
    selected_beta =portfolio_beta.loc[:,start_swan:end_swan].dropna()
    Y_predic = selected_beta[end_swan].copy()
    seed_dict={}

    # Run 1000 trials with davies bouldin index
    for random in range(1,1001):
      Kmean = KMeans(n_clusters=N,random_state=random,n_init=10)
      Kmean.fit(selected_beta)
      labels = Kmean.labels_
      # Evaluate the davies-bouldin score
      dbscore=metrics.davies_bouldin_score(selected_beta, labels)
      seed_dict[random]=dbscore
      sorted_dict=sorted(seed_dict.items(), key=lambda x:x[1])

    # Put all stocks into a stock list
    stock_list=[]
    max_length=0
    for index in range(0,40):
      selected_beta =portfolio_beta.loc[:,start_swan:end_swan].dropna()
      Kmean = KMeans(n_clusters=N,random_state=sorted_dict[index][0],n_init=10)
      Kmean.fit(selected_beta)
      ct = Kmean.cluster_centers_
      Kmean.labels_
      selected_beta["Group"]=Kmean.labels_
      res = ct.mean(axis=1)
      res [res<0]=0
      min_group = np.where(res==min(res))
      for i in range(N):
          Y_predic[selected_beta["Group"] == i] = res [i]
      selected_beta ["avg"]=Y_predic.values
      selected_beta=selected_beta.sort_values(by=["avg"])
      first_group=selected_beta[selected_beta["Group"]==selected_beta["Group"][0]]
      if first_group.shape[0] <10:
          second_group = selected_beta[selected_beta["Group"]==selected_beta["Group"][first_group.shape[0]]]
          preselected_stock = pd.concat([first_group,second_group],axis=0,ignore_index=False)
      else:
          preselected_stock = first_group
      if preselected_stock.shape[0]>max_length:
        max_length=preselected_stock.shape[0]
      stock_list.extend(preselected_stock.index.values)
    print(stock_list)

    # Count the times each stock appear
    values,counts=np.unique(stock_list,return_counts=True)
    count_dict={}
    preselected_stock=[]
    for t in range(0,len(values)):
      count_dict[values[t]]=counts[t]
    sorted_count=sorted(count_dict.items(), key=lambda x:x[1],reverse=True)
    print(sorted_count)

    d = {'stock':[], 'frequency':[]}
    df = pd.DataFrame(data=d)
    for item in sorted_count:
      df.loc[len(df.index)] = [item[0],item[1]]
    df.to_csv('stock_frequency.csv')

    for p in range(0,min(50,len(sorted_count))):
      if sorted_count[p][1]>=1:
        preselected_stock.append(sorted_count[p][0])

    preselected_stock = sorted(preselected_stock)
    selected_beta=selected_beta.loc[preselected_stock]
    selected_beta["avg"]=selected_beta.loc[:,start_swan:end_swan].mean(axis=1)
    # selected_beta['avg']=selected_beta['avg'].mean()
    preselected_stock = selected_beta
    print(preselected_stock)

['DLTR', 'GIS', 'WMT', 'GILD', 'MNST', 'MKTX', 'CPB', 'REGN', 'AMGN', 'PG', 'NEM', 'CL', 'MRK', 'LLY', 'KMB', 'KR', 'DPZ', 'CLX', 'VZ', 'ORLY', 'NEM', 'RSG', 'AMT', 'SBUX', 'NEE', 'HSY', 'MKC', 'DTE', 'PSA', 'O', 'CNP', 'FE', 'MKTX', 'DLTR', 'SBAC', 'AWK', 'MCD', 'AZO', 'HRL', 'PPL', 'CMS', 'KO', 'ATO', 'ICE', 'XEL', 'ES', 'CHD', 'AAP', 'PNW', 'EXC', 'CCI', 'PEAK', 'WEC', 'PEG', 'SO', 'D', 'DUK', 'SRE', 'WELL', 'AEP', 'CINF', 'EVRG', 'ETR', 'MDLZ', 'PEP', 'LNT', 'NI', 'AEE', 'ED', 'ES', 'FE', 'MCD', 'SO', 'EXC', 'ORLY', 'EVRG', 'ETR', 'AWK', 'AZO', 'MDLZ', 'SBAC', 'ED', 'PNW', 'MKC', 'CLX', 'WEC', 'DUK', 'DTE', 'DLTR', 'VZ', 'NI', 'CCI', 'D', 'NEM', 'NEE', 'CHD', 'MKTX', 'AMT', 'ATO', 'AEE', 'HRL', 'ICE', 'AEP', 'CMS', 'CPB', 'KMB', 'KO', 'LNT', 'SRE', 'HSY', 'PPL', 'AAP', 'XEL', 'PEG', 'PEP', 'DUK', 'MCD', 'SBAC', 'MDLZ', 'SO', 'ETR', 'XEL', 'AMT', 'EVRG', 'EXC', 'D', 'ORLY', 'PNW', 'AZO', 'MKC', 'WEC', 'PPL', 'ATO', 'FE', 'CHD', 'NEE', 'SRE', 'ES', 'ICE', 'PEG', 'AAP', 'WM', 'ED', 'CNP', 'PEP', 'KO', 'DTE', 'NI', 'AWK', 'HSY', 'CCI', 'AEE', 'AEP', 'HRL', 'SJM', 'CMS', 'LNT', 'PPL', 'NEE', 'WM', 'GIS', 'CHD', 'ATO', 'AWK', 'SBAC', 'AZO', 'CPB', 'WEC', 'MKTX', 'MKC', 'MDLZ', 'MCD', 'CNP', 'CMS', 'VZ', 'LNT', 'SJM', 'LLY', 'HRL', 'DUK', 'HSY', 'ICE', 'KO', 'KMB', 'SO', 'CCI', 'CLX', 'FE', 'NEM', 'SRE', 'AMT', 'ES', 'ETR', 'PNW', 'ED', 'EVRG', 'XEL', 'AEP', 'DTE', 'ORLY', 'AEE', 'PEG', 'EXC', 'D', 'NI', 'PEP', 'DLTR', 'PG', 'AAP', 'MCD', 'EVRG', 'ETR', 'ES', 'VZ', 'ED', 'DUK', 'DTE', 'DLTR', 'ATO', 'ORLY', 'AWK', 'AZO', 'AMT', 'D', 'PPL', 'SBAC', 'PEG', 'CPB', 'CNP', 'PNW', 'CMS', 'PEP', 'CLX', 'CHD', 'PG', 'WEC', 'SJM', 'EXC', 'SO', 'FE', 'AAP', 'MDLZ', 'LNT', 'LLY', 'MKC', 'MKTX', 'KO', 'KMB', 'AEP', 'SRE', 'AEE', 'CCI', 'ICE', 'XEL', 'HSY', 'NI', 'NEM', 'HRL', 'NEE', 'PSA', 'NI', 'NEE', 'RSG', 'KO', 'HRL', 'AWK', 'SBAC', 'AZO', 'SBUX', 'HSY', 'ICE', 'WM', 'D', 'MKC', 'WELL', 'MDLZ', 'SJM', 'CMS', 'WEC', 'MCD', 'SRE', 'ED', 'LNT', 'CCI', 'SO', 'CHD', 'CNP', 'AMT', 'ATO', 'AEP', 'PPL', 'AAP', 'PNW', 'ES', 'ETR', 'DUK', 'DTE', 'EVRG', 'PEP', 'AEE', 'PEG', 'PEAK', 'EXC', 'CINF', 'XEL', 'FE', 'ORLY', 'O', 'ES', 'D', 'CHD', 'MKTX', 'ATO', 'HSY', 'MKC', 'AWK', 'AZO', 'PNW', 'WEC', 'ICE', 'MDLZ', 'SJM', 'MCD', 'PPL', 'CPB', 'PSA', 'VZ', 'LNT', 'CNP', 'SBUX', 'LLY', 'CMS', 'SBAC', 'RSG', 'CLX', 'KO', 'CCI', 'KMB', 'SO', 'SRE', 'HRL', 'XEL', 'PEG', 'ED', 'AEE', 'AEP', 'PEAK', 'O', 'PG', 'EVRG', 'FE', 'DUK', 'NI', 'EXC', 'PEP', 'DTE', 'NEE', 'ETR', 'DLTR', 'AAP', 'ORLY', 'AMT', 'NEM', 'KO', 'HSY', 'SJM', 'D', 'MCD', 'NEE', 'PSA', 'ATO', 'CPB', 'NEM', 'SBAC', 'AWK', 'ORLY', 'AMT', 'AZO', 'WM', 'SBUX', 'CMS', 'NI', 'O', 'ICE', 'WELL', 'CHD', 'WEC', 'LNT', 'CCI', 'HRL', 'CNP', 'SRE', 'VZ', 'DLTR', 'KMB', 'AAP', 'PNW', 'EXC', 'EVRG', 'ETR', 'MKC', 'MKTX', 'SO', 'ES', 'MDLZ', 'AEE', 'ED', 'AEP', 'FE', 'PEAK', 'RSG', 'DUK', 'XEL', 'PEP', 'PPL', 'DTE', 'PG', 'PEG', 'MCD', 'LNT', 'NI', 'FE', 'DUK', 'ATO', 'DTE', 'PNW', 'AWK', 'AZO', 'SBAC', 'ICE', 'MDLZ', 'HSY', 'D', 'PEG', 'O', 'HRL', 'WEC', 'CCI', 'EXC', 'MKC', 'CHD', 'SJM', 'ORLY', 'CMS', 'AMT', 'SRE', 'CNP', 'SO', 'KO', 'NEE', 'AEP', 'AEE', 'PPL', 'ED', 'AAP', 'ES', 'XEL', 'EVRG', 'SJM', 'ATO', 'AWK', 'KO', 'AZO', 'SBUX', 'PPL', 'ICE', 'SBAC', 'HRL', 'PSA', 'RSG', 'WM', 'CCI', 'WELL', 'WEC', 'CHD', 'SO', 'D', 'SRE', 'DTE', 'DUK', 'ED', 'ES', 'PNW', 'CNP', 'CMS', 'EVRG', 'EXC', 'PEG', 'FE', 'CINF', 'ETR', 'LNT', 'HSY', 'NEE', 'MDLZ', 'MCD', 'O', 'NI', 'PEP', 'XEL', 'AMT', 'MKC', 'AEE', 'AAP', 'PEAK', 'AEP', 'ORLY', 'FE', 'ATO', 'SRE', 'WM', 'AWK', 'NI', 'PEAK', 'ICE', 'HSY', 'HRL', 'PPL', 'WELL', 'WEC', 'O', 'EXC', 'NEE', 'EVRG', 'ES', 'CCI', 'ED', 'DUK', 'PEP', 'DTE', 'PSA', 'CHD', 'CINF', 'ORLY', 'D', 'PEG', 'CMS', 'CNP', 'ETR', 'SO', 'AZO', 'MDLZ', 'MCD', 'XEL', 'AAP', 'LNT', 'SJM', 'SBUX', 'KO', 'AMT', 'SBAC', 'AEP', 'PNW', 'RSG', 'AEE', 'MKC', 'EVRG', 'ETR', 'ES', 'ED', 'PNW', 'DUK', 'DTE', 'DLTR', 'PPL', 'EXC', 'D', 'CNP', 'CMS', 'CLX', 'CHD', 'VZ', 'CCI', 'WEC', 'WM', 'CPB', 'AZO', 'FE', 'HRL', 'SBAC', 'NI', 'NEM', 'NEE', 'SJM', 'MKTX', 'MKC', 'SO', 'GIS', 'MDLZ', 'SRE', 'PEG', 'LNT', 'PEP', 'KO', 'KMB', 'ICE', 'HSY', 'MCD', 'AWK', 'ORLY', 'XEL', 'AEP', 'AMT', 'AAP', 'ATO', 'AEE']
[('AAP', 12), ('AEE', 12), ('AEP', 12), ('AMT', 12), ('ATO', 12), ('AWK', 12), ('AZO', 12), ('CCI', 12), ('CHD', 12), ('CMS', 12), ('D', 12), ('DTE', 12), ('DUK', 12), ('ED', 12), ('ES', 12), ('EVRG', 12), ('EXC', 12), ('FE', 12), ('HRL', 12), ('HSY', 12), ('ICE', 12), ('KO', 12), ('LNT', 12), ('MCD', 12), ('MDLZ', 12), ('MKC', 12), ('NEE', 12), ('NI', 12), ('ORLY', 12), ('PEG', 12), ('PNW', 12), ('PPL', 12), ('SBAC', 12), ('SO', 12), ('SRE', 12), ('WEC', 12), ('XEL', 12), ('CNP', 11), ('ETR', 11), ('PEP', 11), ('SJM', 10), ('DLTR', 8), ('MKTX', 8), ('NEM', 8), ('CPB', 7), ('KMB', 7), ('O', 7), ('VZ', 7), ('WM', 7), ('CLX', 6), ('PEAK', 6), ('PSA', 6), ('RSG', 6), ('SBUX', 6), ('PG', 5), ('WELL', 5), ('CINF', 4), ('LLY', 4), ('GIS', 3), ('AMGN', 1), ('CL', 1), ('DPZ', 1), ('GILD', 1), ('KR', 1), ('MNST', 1), ('MRK', 1), ('REGN', 1), ('WMT', 1)]
             Swan5     Swan6     Swan7     Swan8     Swan9  Group       avg
stickers
AAP       0.207075 -0.048495 -0.125923  0.578707  1.299581      9  0.382189
AEE       1.139264 -0.008178 -0.139507  0.001824  0.833510      9  0.365382
AEP       0.764573  0.012211  0.305260 -0.296070  0.959958      9  0.349186
AMT       0.569595  0.048213  0.653109 -0.349966  0.824960      9  0.349182
ATO       0.548668  0.468099 -0.135669  0.164407  0.959928      9  0.401086
AWK       0.315968 -0.006396 -0.054045  0.054179  0.890179      9  0.239977
AZO      -0.451106 -0.302805 -0.147542 -0.403255  0.955177      9 -0.069906
CCI       1.078170  0.276796  0.251913  0.188927  0.854298      9  0.530021
CHD       0.597611 -0.086318  0.238837 -0.333092  0.583540      9  0.200115
CLX       0.576575  0.697814  0.236833  0.031918 -0.095359      9  0.289556
CMS       0.323398  0.149971  0.087545  0.016945  0.864892      9  0.288550
CNP       0.846554  0.242577  0.267542 -0.032564  1.608039      9  0.586430
CPB       0.728954  0.190088  0.257472  0.396142  0.301611      9  0.374853
D         0.802585 -0.063489 -0.113903 -0.120577  0.938628      9  0.288649
DLTR     -0.244035 -0.399881  0.862884 -0.114957  0.503603      9  0.121523
DTE       0.976909  0.282935  0.092192 -0.056867  1.247592      9  0.508552
DUK       0.753130 -0.306652  0.261517 -0.370330  1.089892      9  0.285511
ED        0.522846 -0.369009 -0.192318  0.007206  0.901315      9  0.174008
ES        0.530864  0.478169  0.058232 -0.234628  0.996690      9  0.365865
ETR       0.734601  0.232165  0.918211 -0.246784  1.223640      9  0.572366
EVRG      0.762814  0.150108  0.011663 -0.139129  1.150500      9  0.387191
EXC       0.775538  0.250219  0.677286 -0.128316  1.173181      9  0.549582
FE        1.021036  0.025132  0.471488  0.072718  1.078280      9  0.533731
HRL       0.305466  0.693729 -0.133501 -0.186106  0.375322      9  0.210982
HSY       0.528522  0.023717  0.519845 -0.100157  0.896658      9  0.373717
ICE       0.441688  0.478450  0.326035  0.275637  0.880485      9  0.480459
KMB       0.719477 -0.287423  0.712938  0.218981  0.631523      9  0.399099
KO        0.507952  0.309668  0.687838 -0.051484  1.085734      9  0.507942
LNT       0.865457  0.355652  0.506648  0.126184  0.971491      9  0.565086
MCD       0.314079  0.123567  0.540851 -0.210976  1.068325      9  0.367169
MDLZ      0.808367  0.326994  0.100409  0.401756  0.868746      9  0.501254
MKC       0.518681  0.591668  0.418703 -0.021205  0.907670      9  0.483103
MKTX      0.399881  0.214649  0.985512 -0.471938  0.524022      9  0.330425
NEE       0.491760  0.394598  0.214891 -0.027690  0.994062      9  0.413524
NEM       0.233639 -0.467379  0.920061 -0.725163  0.282156      9  0.048663
NI        0.998797 -0.008673  0.279552 -0.056571  0.904967      9  0.423614
O         0.964225  0.583043  0.451379 -0.362587  1.347101      5  0.596632
ORLY     -0.297526 -0.249819  0.297465  0.243959  0.992495      9  0.197315
PEG       0.640054  0.023724  0.294489  0.171683  1.093031      9  0.444596
PEP       0.793869  0.423638  0.661784  0.031393  0.807842      9  0.543705
PNW       0.763766  0.246101  0.085306 -0.435912  1.128328      9  0.357518
PPL       0.720678 -0.020615  0.135247  0.281188  1.374079      9  0.498115
SBAC      0.615326  0.717906  0.153646 -0.118575  0.757587      9  0.425178
SJM       0.672289  0.567134  0.043394  0.398177  0.398536      9  0.415906
SO        0.653423 -0.265818  0.061754 -0.095444  1.097114      9  0.290206
SRE       0.683623  0.206838  0.446883  0.328070  1.213348      9  0.575752
VZ        0.324329  0.060847  0.802959  0.062562  0.402950      9  0.330730
WEC       0.375244  0.064560  0.053054 -0.106203  0.912834      9  0.259898
WM        0.731543  0.665585 -0.107269  0.313536  0.875331      9  0.495745
XEL       0.468746 -0.003058  0.100311 -0.161306  0.857456      9  0.252430

In [ ]:
ct

array([[ 0.82311856,  0.58831482,  0.97881998,  0.50156887,  0.78398758],
       [ 1.5761811 ,  2.37567765,  1.6191697 ,  1.45117568,  1.43137724],
       [ 1.01125011,  1.32971637,  0.79006   ,  1.08251784,  0.80042428],
       [ 1.34395054,  0.89375745,  0.80574194,  1.00395245,  1.57329361],
       [ 1.62840535,  2.02860979,  0.37186388,  0.71610996,  1.37800633],
       [ 1.15120899,  0.90481416,  0.58181678,  0.03008322,  1.25360701],
       [ 0.7985181 ,  0.38236479,  0.50108004,  1.24984179,  0.68574542],
       [ 0.64752718,  0.6853599 ,  1.77695548,  1.28910494,  1.09074067],
       [ 1.28688361,  1.5267788 ,  1.258259  ,  1.05934866,  1.21405049],
       [ 0.57564548,  0.14157641,  0.28300635, -0.01249442,  0.87555477],
       [ 0.61290929,  2.05497814,  0.23854383,  1.81440495,  0.91505371],
       [ 1.05184745,  2.0448101 ,  1.14664414,  2.24751236,  1.95151203],
       [ 1.70903541,  2.25591019, -2.5332745 ,  1.77515459,  0.62814325],
       [ 0.43910653,  0.87733728,  0.70301835,  0.8743975 ,  1.11316901],
       [ 1.67219944,  1.59227878,  1.04780841,  1.64366717,  1.57449586],
       [ 0.90855972,  1.13462976, -0.15751874,  0.91141851,  1.1507442 ],
       [ 1.25186685,  2.22158316,  3.17442947,  2.16899094,  1.93732031]])

In [ ]:
res

array([0.73516196, 1.69071628, 1.00279372, 1.1241392 , 1.22459906,
       0.78430603, 0.72351003, 1.09793764, 1.26906411, 0.37265772,
       1.12717798, 1.68846522, 0.76699379, 0.80140574, 1.50608993,
       0.78956669, 2.15083815])

In [ ]:
preselected_stock.info()

<class 'pandas.core.frame.DataFrame'>
Index: 50 entries, AAP to XEL
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Swan5   50 non-null     float64
 1   Swan6   50 non-null     float64
 2   Swan7   50 non-null     float64
 3   Swan8   50 non-null     float64
 4   Swan9   50 non-null     float64
 5   Group   50 non-null     int32
 6   avg     50 non-null     float64
dtypes: float64(6), int32(1)
memory usage: 2.9+ KB

In [ ]:
#portfolio_beta["avg"]=portfolio_beta.loc[:,start_swan:end_swan]*weight

In [ ]:
preselected_stock["PR"]=1-preselected_stock["avg"]
preselected_stock.to_csv('preselected_stocks.csv')
preselected_stock

,Swan5,Swan6,Swan7,Swan8,Swan9,Group,avg,PR
stickers,,,,,,,,
AAP,0.207075,-0.048495,-0.125923,0.578707,1.299581,9,0.382189,0.617811
AEE,1.139264,-0.008178,-0.139507,0.001824,0.833510,9,0.365382,0.634618
AEP,0.764573,0.012211,0.305260,-0.296070,0.959958,9,0.349186,0.650814
AMT,0.569595,0.048213,0.653109,-0.349966,0.824960,9,0.349182,0.650818
ATO,0.548668,0.468099,-0.135669,0.164407,0.959928,9,0.401086,0.598914
AWK,0.315968,-0.006396,-0.054045,0.054179,0.890179,9,0.239977,0.760023
AZO,-0.451106,-0.302805,-0.147542,-0.403255,0.955177,9,-0.069906,1.069906
CCI,1.078170,0.276796,0.251913,0.188927,0.854298,9,0.530021,0.469979
CHD,0.597611,-0.086318,0.238837,-0.333092,0.583540,9,0.200115,0.799885
CLX,0.576575,0.697814,0.236833,0.031918,-0.095359,9,0.289556,0.710444
CMS,0.323398,0.149971,0.087545,0.016945,0.864892,9,0.288550,0.711450
CNP,0.846554,0.242577,0.267542,-0.032564,1.608039,9,0.586430,0.413570
CPB,0.728954,0.190088,0.257472,0.396142,0.301611,9,0.374853,0.625147
D,0.802585,-0.063489,-0.113903,-0.120577,0.938628,9,0.288649,0.711351
DLTR,-0.244035,-0.399881,0.862884,-0.114957,0.503603,9,0.121523,0.878477
DTE,0.976909,0.282935,0.092192,-0.056867,1.247592,9,0.508552,0.491448
DUK,0.753130,-0.306652,0.261517,-0.370330,1.089892,9,0.285511,0.714489
ED,0.522846,-0.369009,-0.192318,0.007206,0.901315,9,0.174008,0.825992
ES,0.530864,0.478169,0.058232,-0.234628,0.996690,9,0.365865,0.634135
ETR,0.734601,0.232165,0.918211,-0.246784,1.223640,9,0.572366,0.427634
EVRG,0.762814,0.150108,0.011663,-0.139129,1.150500,9,0.387191,0.612809
EXC,0.775538,0.250219,0.677286,-0.128316,1.173181,9,0.549582,0.450418
FE,1.021036,0.025132,0.471488,0.072718,1.078280,9,0.533731,0.466269
HRL,0.305466,0.693729,-0.133501,-0.186106,0.375322,9,0.210982,0.789018
HSY,0.528522,0.023717,0.519845,-0.100157,0.896658,9,0.373717,0.626283
ICE,0.441688,0.478450,0.326035,0.275637,0.880485,9,0.480459,0.519541
KMB,0.719477,-0.287423,0.712938,0.218981,0.631523,9,0.399099,0.600901
KO,0.507952,0.309668,0.687838,-0.051484,1.085734,9,0.507942,0.492058
LNT,0.865457,0.355652,0.506648,0.126184,0.971491,9,0.565086,0.434914
MCD,0.314079,0.123567,0.540851,-0.210976,1.068325,9,0.367169,0.632831
MDLZ,0.808367,0.326994,0.100409,0.401756,0.868746,9,0.501254,0.498746
MKC,0.518681,0.591668,0.418703,-0.021205,0.907670,9,0.483103,0.516897
MKTX,0.399881,0.214649,0.985512,-0.471938,0.524022,9,0.330425,0.669575
NEE,0.491760,0.394598,0.214891,-0.027690,0.994062,9,0.413524,0.586476
NEM,0.233639,-0.467379,0.920061,-0.725163,0.282156,9,0.048663,0.951337
NI,0.998797,-0.008673,0.279552,-0.056571,0.904967,9,0.423614,0.576386
O,0.964225,0.583043,0.451379,-0.362587,1.347101,5,0.596632,0.403368
ORLY,-0.297526,-0.249819,0.297465,0.243959,0.992495,9,0.197315,0.802685
PEG,0.640054,0.023724,0.294489,0.171683,1.093031,9,0.444596,0.555404
PEP,0.793869,0.423638,0.661784,0.031393,0.807842,9,0.543705,0.456295
PNW,0.763766,0.246101,0.085306,-0.435912,1.128328,9,0.357518,0.642482
PPL,0.720678,-0.020615,0.135247,0.281188,1.374079,9,0.498115,0.501885
SBAC,0.615326,0.717906,0.153646,-0.118575,0.757587,9,0.425178,0.574822
SJM,0.672289,0.567134,0.043394,0.398177,0.398536,9,0.415906,0.584094
SO,0.653423,-0.265818,0.061754,-0.095444,1.097114,9,0.290206,0.709794
SRE,0.683623,0.206838,0.446883,0.328070,1.213348,9,0.575752,0.424248
VZ,0.324329,0.060847,0.802959,0.062562,0.402950,9,0.330730,0.669270
WEC,0.375244,0.064560,0.053054,-0.106203,0.912834,9,0.259898,0.740102
WM,0.731543,0.665585,-0.107269,0.313536,0.875331,9,0.495745,0.504255
XEL,0.468746,-0.003058,0.100311,-0.161306,0.857456,9,0.252430,0.747570

# Step 2 - Download data and adjuste price based on Swan Beta

In [ ]:
#next line is used to input preselected stock from excel, if you are going to preselect by your self, use this blocks and note next one.
#selected_stock_list =  pd.read_excel("19_stickers.xlsx",header = None).values[:,0]
#swan_beta=pd.read_excel("19_stickers.xlsx",header = None,index_col=0).iloc[:,0]

In [ ]:
#Set the paramter to download tradeinfo from Yahoo Finance
selected_stock=preselected_stock
selected_stock_list=selected_stock.index.values
swan_beta=preselected_stock.loc[selected_stock_list,"avg"]
print(selected_stock_list)

['AAP' 'AEE' 'AEP' 'AMT' 'ATO' 'AWK' 'AZO' 'CCI' 'CHD' 'CLX' 'CMS' 'CNP'
 'CPB' 'D' 'DLTR' 'DTE' 'DUK' 'ED' 'ES' 'ETR' 'EVRG' 'EXC' 'FE' 'HRL'
 'HSY' 'ICE' 'KMB' 'KO' 'LNT' 'MCD' 'MDLZ' 'MKC' 'MKTX' 'NEE' 'NEM' 'NI'
 'O' 'ORLY' 'PEG' 'PEP' 'PNW' 'PPL' 'SBAC' 'SJM' 'SO' 'SRE' 'VZ' 'WEC'
 'WM' 'XEL']

In [ ]:
#download data from yahoo finance
yahooDataFrame= pdr.get_data_yahoo(list(selected_stock_list), start=start, end=end)["Adj Close"]

[*********************100%%**********************]  50 of 50 completed

In [ ]:
yahooDataFrame

Ticker,AAP,AEE,AEP,AMT,ATO,AWK,AZO,CCI,CHD,CLX,...,PNW,PPL,SBAC,SJM,SO,SRE,VZ,WEC,WM,XEL
Date,,,,,,,,,,,,,,,,,,,,,
2020-11-02,139.088150,74.613701,79.447807,210.895905,86.600853,144.427719,1141.150024,135.812775,84.117851,193.531815,...,69.026711,23.973215,281.357330,104.086525,50.797901,56.540134,46.420441,91.307068,104.056244,63.899658
2020-11-03,144.646881,75.609062,79.151711,211.564301,88.523102,147.048599,1164.650024,136.553650,85.170517,191.127533,...,69.614220,24.595781,278.951416,104.372040,51.529613,57.195824,46.460670,92.289726,107.854820,64.967926
2020-11-04,142.901154,74.828918,78.507286,214.129486,86.673393,145.466721,1154.020020,138.069489,85.907387,191.748871,...,69.988846,23.811178,289.505188,102.230698,51.443520,56.898983,46.034283,90.129669,109.114731,64.736473
2020-11-05,143.728088,73.950157,78.994965,216.703674,86.156570,148.087570,1149.510010,138.742264,86.156204,191.784882,...,71.930145,23.930574,293.147675,103.319221,51.796471,56.269878,46.782478,89.943764,112.537193,65.635582
2020-11-06,143.682190,73.394218,79.177826,218.717911,84.905289,150.820724,1158.530029,139.721588,86.605972,196.377335,...,71.342644,23.546799,293.914520,104.050842,51.615688,55.304066,47.088181,90.616577,112.151703,65.261703
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-12-27,221.037323,81.150360,79.200851,264.678223,97.510857,174.904892,2047.060059,181.148834,97.446419,157.713242,...,61.268475,27.055386,370.892822,123.967476,60.677647,60.132294,44.302700,87.423470,157.233505,61.562050
2021-12-28,222.560730,81.956741,80.228607,267.206726,96.920502,177.343887,2059.939941,182.520126,97.271622,158.673050,...,62.006645,27.275274,372.218292,125.217789,61.375416,60.423336,44.336346,88.542877,158.529480,62.299099
2021-12-29,225.271118,82.410942,80.565117,267.567993,98.232391,178.534836,2104.040039,183.404877,98.048401,158.165482,...,62.140049,27.293596,372.431213,125.125198,61.683514,60.728252,44.033588,88.928253,159.719849,62.612343
2021-12-30,221.990616,82.549980,80.665169,269.661316,97.913803,179.144577,2084.520020,183.953400,98.475632,159.032990,...,62.700352,27.440187,375.923706,125.347458,61.946308,60.876091,43.941078,89.111740,159.095840,62.861099
2021-12-31,224.196304,82.503654,80.919838,270.920929,98.176147,179.935349,2096.389893,184.678894,99.524269,160.915680,...,62.780396,27.540970,376.368774,125.792023,62.145657,61.111698,43.697189,89.065887,160.219025,62.372799

In [ ]:
#set parameters to calculate predict market drop
market_drop_info = pd.read_excel("MarketDD.xlsx",index_col=0)
#swan_to_predict=100
total_day=yahooDataFrame.shape[0]
t1=int(round(market_drop_info.loc[:end_swan,"T1"].mean(),0))
t1=int((np.array(market_drop_info.loc[:end_swan,"T1"])*np.array(weight_swan)).sum())
#t2=total_day-t1
t2=int(round(market_drop_info.loc[:end_swan,"T2"].mean(),0))
dd=market_drop_info.loc[:end_swan,"Actual DD"].mean()
t0=int(total_day-t1-t2)

In [ ]:
#calculate predict market drop
md = [] #Make market drop data list named md


j = 0 #Start from 0
inc = dd/(t1-1) #Calculate unit increasing market drop
for i in range(t1): #Append market drop data for t1
    md.append(round(j,4))
    j = j + inc

base = (t2+1)**(1/(dd*100)) #Calculate log base
l1 = [] #Make decreasing market drop list
for i in range(t2):
    l1.append(math.log((i+2),base)/100)

for i in range(t2): #Append market drop data for t2
    md.append(round((dd-l1[i]),4))

for i in range(t0):
    md.append(0)

market_drop = pd.DataFrame(md) #Change list into dataframe
#market_drop = market_drop.rename(columns={0: 'Swan Drop spy'}) #Change column name
market_drop1 = pd.read_csv("trainingMarketdrop.csv")

In [ ]:
market_drop.to_csv("market_drop.csv")

In [ ]:
market_drop

          0
0    0.0000
1    0.0045
2    0.0089
3    0.0134
4    0.0179
..      ...
289  0.0000
290  0.0000
291  0.0000
292  0.0000
293  0.0000

[294 rows x 1 columns]

In [ ]:
swan_drop_pct=np.array(swan_beta)*np.array(market_drop)
yahooDataFrame=pd.DataFrame((1-swan_drop_pct)*np.array(yahooDataFrame),index=yahooDataFrame.index,columns=yahooDataFrame.columns)

In [ ]:
yahooDataFrame

Ticker,AAP,AEE,AEP,AMT,ATO,AWK,AZO,CCI,CHD,CLX,...,PNW,PPL,SBAC,SJM,SO,SRE,VZ,WEC,WM,XEL
Date,,,,,,,,,,,,,,,,,,,,,
2020-11-02,139.088150,74.613701,79.447807,210.895905,86.600853,144.427719,1141.150024,135.812775,84.117851,193.531815,...,69.026711,23.973215,281.357330,104.086525,50.797901,56.540134,46.420441,91.307068,104.056244,63.899658
2020-11-03,144.398110,75.484744,79.027336,211.231865,88.363327,146.889802,1165.016398,136.227957,85.093819,190.878493,...,69.502222,24.540649,278.417698,104.176700,51.462320,57.047636,46.391524,92.181790,107.614212,64.894127
2020-11-04,142.415078,74.585582,78.263304,213.464031,86.363998,145.156033,1154.738011,137.418189,85.754383,191.254725,...,69.766148,23.705618,288.409676,101.852284,51.310650,56.607421,45.898781,89.921191,108.633302,64.591035
2020-11-05,142.992009,73.588088,78.625340,215.689709,85.693517,147.611366,1150.586807,137.756878,85.925172,191.040746,...,71.585547,23.770844,291.477500,102.743409,51.595047,55.835752,46.575149,89.630523,111.789610,65.413566
2020-11-06,142.699234,72.914195,78.682930,217.350845,84.295716,150.172860,1159.979724,138.395998,86.295744,195.359500,...,70.886082,23.336849,291.677630,103.276213,51.347561,54.734104,46.809416,90.195013,111.156487,64.966819
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-12-27,221.037323,81.150360,79.200851,264.678223,97.510857,174.904892,2047.060059,181.148834,97.446419,157.713242,...,61.268475,27.055386,370.892822,123.967476,60.677647,60.132294,44.302700,87.423470,157.233505,61.562050
2021-12-28,222.560730,81.956741,80.228607,267.206726,96.920502,177.343887,2059.939941,182.520126,97.271622,158.673050,...,62.006645,27.275274,372.218292,125.217789,61.375416,60.423336,44.336346,88.542877,158.529480,62.299099
2021-12-29,225.271118,82.410942,80.565117,267.567993,98.232391,178.534836,2104.040039,183.404877,98.048401,158.165482,...,62.140049,27.293596,372.431213,125.125198,61.683514,60.728252,44.033588,88.928253,159.719849,62.612343
2021-12-30,221.990616,82.549980,80.665169,269.661316,97.913803,179.144577,2084.520020,183.953400,98.475632,159.032990,...,62.700352,27.440187,375.923706,125.347458,61.946308,60.876091,43.941078,89.111740,159.095840,62.861099
2021-12-31,224.196304,82.503654,80.919838,270.920929,98.176147,179.935349,2096.389893,184.678894,99.524269,160.915680,...,62.780396,27.540970,376.368774,125.792023,62.145657,61.111698,43.697189,89.065887,160.219025,62.372799

In [ ]:
yahooDataFrame=yahooDataFrame.dropna(how="all",axis = 1)
selected_stock_list=yahooDataFrame.columns.values
selected_stock_number = yahooDataFrame.shape[1]
selected_stock_list

array(['AAP', 'AEE', 'AEP', 'AMT', 'ATO', 'AWK', 'AZO', 'CCI', 'CHD',
       'CLX', 'CMS', 'CNP', 'CPB', 'D', 'DLTR', 'DTE', 'DUK', 'ED', 'ES',
       'ETR', 'EVRG', 'EXC', 'FE', 'HRL', 'HSY', 'ICE', 'KMB', 'KO',
       'LNT', 'MCD', 'MDLZ', 'MKC', 'MKTX', 'NEE', 'NEM', 'NI', 'O',
       'ORLY', 'PEG', 'PEP', 'PNW', 'PPL', 'SBAC', 'SJM', 'SO', 'SRE',
       'VZ', 'WEC', 'WM', 'XEL'], dtype=object)

# Step3 - MVO

In [ ]:
#Set the paramter for MVO process
Portfolio_Date=end

In [ ]:
#data cleaning - filling missing data in yahooDataFrame
data_cleaning(yahooDataFrame)

In [ ]:
#calculated rf
bond_yield = quandl.get('FRED/DGS3MO')
bond_yield=np.log(bond_yield/100+1)
date=list(map(str,bond_yield.index.values))
date=list(map(modify_date,date))
week=pd.to_datetime(date).strftime("%W").values
week_1=np.roll(week,1)
week_difference=np.where(week!=week_1)
week_difference=np.delete(week_difference,0,None)
rf_week=bond_yield.iloc[week_difference-1]

In [ ]:
# Calculated R for 1 year and 0.5 year
today_price = yahooDataFrame.iloc[-MA_days:,:]
one_year_ago_data = get_price_years_ago(yahooDataFrame,end,1)
one_year_ago_date = one_year_ago_data.index.values[-1]
half_year_ago_data = get_price_years_ago(yahooDataFrame,end,0.5)
half_year_ago_date = half_year_ago_data.index.values[-1]
one_year_ago_price=yahooDataFrame.loc[one_year_ago_date:,:]
one_year_ago_price=yahooDataFrame.iloc[:MA_days,:]
half_year_ago_price=yahooDataFrame.loc[half_year_ago_date:,:]
half_year_ago_price=yahooDataFrame.iloc[:MA_days,:]

R_mv_one_year=np.mean(pd.DataFrame(np.array(today_price)/np.array(one_year_ago_price)-1,index=today_price.index,columns=today_price.columns),axis=0)
R_mv_half_year=np.mean(pd.DataFrame(np.array(today_price)/np.array(half_year_ago_price)-1,index=today_price.index,columns=today_price.columns),axis=0)

In [ ]:
# Calculate MA
MA_Data=yahooDataFrame.rolling(MA_days).mean().dropna(axis=0)
MA_Data=MA_Data.loc[one_year_ago_date:,:]
MA_now = MA_Data.iloc[-1,:]
MA_one_year_ago = MA_Data.iloc[0,:]
MA_half_year_ago = MA_Data.loc[half_year_ago_date,:]

In [ ]:
# Calculate daily return
daily_return = yahooDataFrame.pct_change().dropna()
log_daily_return = np.log(1+daily_return)

# Get week end stock price data
stock_date = yahooDataFrame.index.values
week=pd.to_datetime(stock_date).strftime("%W").values
week_1=np.roll(week,1)
week_difference=np.where(week!=week_1)
week_difference=np.delete(week_difference,0,None)
# Calculate weekly return

weekly_return=yahooDataFrame.iloc[week_difference-1].pct_change().dropna()
log_weekly_return = np.log(1+weekly_return)

# Get month end stock price data
stock_date = yahooDataFrame.index.values
month=pd.to_datetime(stock_date).strftime("%m").values
month_1=np.roll(month,1)
month_difference=np.where(month!=month_1)
month_difference=np.delete(month_difference,0,None)
# Calculate monthly return
monthly_return=yahooDataFrame.iloc[month_difference-1].pct_change().dropna()
log_monthly_return = np.log(1+monthly_return)

# Get semi-month end stock price data
semi_month = []
for i in range(1,len(month_difference)):
    semi_month.append((month_difference[i]-month_difference[i-1])//2+month_difference[i-1])
    semi_month.append(month_difference[i]-1)
# Calculate semi-monthly return
semi_monthly_return=yahooDataFrame.iloc[semi_month].pct_change().dropna()
log_semi_monthly_return = np.log(1+semi_monthly_return)

In [ ]:
# Calculated Max Dropdown for each stock
stock_return_one_year=daily_return.loc[one_year_ago_date:,:]
mdd=[]
for column in stock_return_one_year.columns:
    mdd .append(max_drawdown_absolute(stock_return_one_year.loc[:,column]))
mdd=pd.DataFrame(mdd,index = stock_return_one_year.columns,columns=["MAXDD","start_index","end_index"])
mar=R_mv_one_year/mdd.iloc[:,0]

In [ ]:
#calculate weekly sd for each stock
one_year_weekly_return=log_weekly_return.iloc[log_weekly_return.index >= one_year_ago_date]
weekly_std= np.std(one_year_weekly_return)*np.sqrt(one_year_weekly_return.shape[0])

#Calculate garch_std sd for each stock
one_year_monthly_return=log_monthly_return.iloc[log_monthly_return.index >= one_year_ago_date]
res_all = one_year_monthly_return - np.mean(one_year_monthly_return)
judge = one_year_monthly_return.shape[0]
for stock in one_year_monthly_return.columns:
    res=res_all[stock]
    h= het_arch(res)
    if judge < 100 or h ==0:
        garch_std = weekly_std

    else:#build Garch Model
        std = []
        if judge <=200:
            p = 0
            q = 6
        else:
            p = 1
            q = 1

        std.append(fit_garch(one_year_monthly_return[stock],p,q))
        garch_std = pd.DataFrame(std,index = one_year_monthly_return.columns)

#Calculate monthly sd for each stock
one_year_monthly_return=log_monthly_return.iloc[log_monthly_return.index >= one_year_ago_date]
monthly_std = np.std(one_year_monthly_return)*np.sqrt(12);

#Calculate semi_monthly sd for each stock
one_year_semi_monthly_return=log_semi_monthly_return.iloc[log_semi_monthly_return.index >= one_year_ago_date]
semi_monthly_std = np.std(one_year_semi_monthly_return)*np.sqrt(24);

In [ ]:
# Calculated MaxDrop
DD_range = 90
total_range = 90
DD_end = yahooDataFrame.iloc[yahooDataFrame.index <= one_year_ago_date]
DD_start = yahooDataFrame.iloc[yahooDataFrame.index <= end-datetime.timedelta(total_range)]
max_DD=[-1]*selected_stock_number


if (DD_start.shape[0] != 1 ) and (DD_end.shape[0] != 1):
    DD_start = DD_start.index[-1]
    DD_end = DD_end.index[-1]
    while DD_start > DD_end :
        DD_start = yahooDataFrame.iloc[yahooDataFrame.index <= end-datetime.timedelta(total_range)]
        DD_mid = yahooDataFrame.iloc[yahooDataFrame.index <= end-datetime.timedelta(DD_range+total_range)]
        if (DD_start.shape[0] != 1 ) and (DD_mid.shape[0] != 1):
            DD_start = DD_start.index[-1]
            DD_mid = DD_mid.index[-1]
            price = yahooDataFrame.loc[DD_start:DD_mid,:]
            for i in range(len(yahooDataFrame.columns)):
                max_DD[i]=max(max_DD[i],max_drawdown_absolute(stock_return_one_year.iloc[:,i])[0])
            total_range = total_range + 1
        else:
            break

In [ ]:
# Read OPT-data
optdata = pd.read_excel("optdata_SP500_20220103.xlsx",index_col=0,sheet_name = 0)
P_current = MA_now
P_fwd = optdata.P_fwd.loc[P_current.index]
R_fwd=P_fwd/P_current-1
R_60 = P_current/MA_one_year_ago - 1
R_60_half = P_current/MA_half_year_ago - 1
R_MA_1ago = R_mv_one_year
R_MA_halfago = R_mv_half_year
Rfwd_adjusted = pd.Series(index=R_MA_1ago.index)
for i in R_fwd.index:
    if R_fwd[i] < 0.5*R_60[i]:
        Rfwd_adjusted[i] = R_60_half[i]
    elif R_fwd[i] > 1.3*R_60[i]:
        if 1.3*R_60[i] > 0.7*R_fwd[i]:
            Rfwd_adjusted[i] = 1.3*R_60[i]
        else:
            Rfwd_adjusted[i] = 0.7*R_fwd[i]
    else:
        Rfwd_adjusted[i] = R_fwd[i]
Rfwd_adjusted[Rfwd_adjusted<0]=0

In [ ]:
price_now = today_price.iloc[-1,:]
optimizer = optdata.loc[P_current.index,:]
FFC = pd.DataFrame([R_MA_1ago.values,R_MA_halfago.values,MA_now.values,price_now.values,semi_monthly_std.values,weekly_std.values,MA_one_year_ago.values,MA_half_year_ago.values,max_DD,R_60.values,R_60_half.values,P_fwd.values,Rfwd_adjusted.values],columns = R_MA_1ago.index,index = ["R_MA_1ago","R_MA_halfago","MA_now","price",'std','std_f','MA_1ago','MA_halfago','Fall_MDD','R_60','R_60_half','R_fwd',"Rfwd_adjusted"]).T
preselected_stock = preselected_stock.loc[selected_stock_list,:]
preselected_stock["Rfwd_adjusted"]=Rfwd_adjusted.values
preselected_stock["std_f"]=weekly_std.values
preselected_stock["SR"]=preselected_stock["Rfwd_adjusted"]/preselected_stock["std_f"]
preselected_stock["PR_SR"]=preselected_stock["PR"]*preselected_stock["SR"]**0.5
preselected_stock.to_csv("preselected_Stocks_info.csv")
p=FFC.MA_now
EPS_fwd=optimizer.EPS_fwd
EPS_ttm=optimizer.EPS_ttm
fall=FFC.Fall_MDD
FFC.to_csv("WEDataBank.csv")

PE=p/EPS_fwd
PEG= p/(EPS_fwd*(EPS_fwd/EPS_ttm-1))
PEG[PEG<0]=2000

In [ ]:
preselected_stock

,Swan5,Swan6,Swan7,Swan8,Swan9,Group,avg,PR,Rfwd_adjusted,std_f,SR,PR_SR
stickers,,,,,,,,,,,,
AAP,0.207075,-0.048495,-0.125923,0.578707,1.299581,9,0.382189,0.617811,0.206087,0.262889,0.783932,0.547009
AEE,1.139264,-0.008178,-0.139507,0.001824,0.833510,9,0.365382,0.634618,0.145098,0.169984,0.853600,0.586326
AEP,0.764573,0.012211,0.305260,-0.296070,0.959958,9,0.349186,0.650814,0.177847,0.165063,1.077449,0.675546
AMT,0.569595,0.048213,0.653109,-0.349966,0.824960,9,0.349182,0.650818,0.206995,0.215074,0.962434,0.638476
ATO,0.548668,0.468099,-0.135669,0.164407,0.959928,9,0.401086,0.598914,0.148051,0.212828,0.695638,0.499524
AWK,0.315968,-0.006396,-0.054045,0.054179,0.890179,9,0.239977,0.760023,0.150622,0.199392,0.755403,0.660566
AZO,-0.451106,-0.302805,-0.147542,-0.403255,0.955177,9,-0.069906,1.069906,0.366687,0.263963,1.389165,1.261022
CCI,1.078170,0.276796,0.251913,0.188927,0.854298,9,0.530021,0.469979,0.180552,0.212659,0.849020,0.433050
CHD,0.597611,-0.086318,0.238837,-0.333092,0.583540,9,0.200115,0.799885,0.143704,0.135848,1.057825,0.822686
CLX,0.576575,0.697814,0.236833,0.031918,-0.095359,9,0.289556,0.710444,0.020772,0.197433,0.105211,0.230441
CMS,0.323398,0.149971,0.087545,0.016945,0.864892,9,0.288550,0.711450,0.139669,0.165353,0.844669,0.653864
CNP,0.846554,0.242577,0.267542,-0.032564,1.608039,9,0.586430,0.413570,0.117224,0.221538,0.529138,0.300839
CPB,0.728954,0.190088,0.257472,0.396142,0.301611,9,0.374853,0.625147,0.145163,0.180280,0.805209,0.560966
D,0.802585,-0.063489,-0.113903,-0.120577,0.938628,9,0.288649,0.711351,0.183761,0.161717,1.136310,0.758285
DLTR,-0.244035,-0.399881,0.862884,-0.114957,0.503603,9,0.121523,0.878477,0.374409,0.355855,1.052138,0.901087
DTE,0.976909,0.282935,0.092192,-0.056867,1.247592,9,0.508552,0.491448,0.212567,0.150015,1.416973,0.585003
DUK,0.753130,-0.306652,0.261517,-0.370330,1.089892,9,0.285511,0.714489,0.181156,0.149090,1.215082,0.787586
ED,0.522846,-0.369009,-0.192318,0.007206,0.901315,9,0.174008,0.825992,0.106360,0.150000,0.709068,0.695537
ES,0.530864,0.478169,0.058232,-0.234628,0.996690,9,0.365865,0.634135,0.115355,0.176445,0.653773,0.512738
ETR,0.734601,0.232165,0.918211,-0.246784,1.223640,9,0.572366,0.427634,0.194103,0.227349,0.853769,0.395132
EVRG,0.762814,0.150108,0.011663,-0.139129,1.150500,9,0.387191,0.612809,0.191225,0.155944,1.226239,0.678598
EXC,0.775538,0.250219,0.677286,-0.128316,1.173181,9,0.549582,0.450418,0.484444,0.178715,2.710706,0.741579
FE,1.021036,0.025132,0.471488,0.072718,1.078280,9,0.533731,0.466269,0.084313,0.188501,0.447282,0.311837
HRL,0.305466,0.693729,-0.133501,-0.186106,0.375322,9,0.210982,0.789018,0.057791,0.174492,0.331198,0.454078
HSY,0.528522,0.023717,0.519845,-0.100157,0.896658,9,0.373717,0.626283,0.088725,0.126165,0.703241,0.525198
ICE,0.441688,0.478450,0.326035,0.275637,0.880485,9,0.480459,0.519541,0.198709,0.195973,1.013957,0.523154
KMB,0.719477,-0.287423,0.712938,0.218981,0.631523,9,0.399099,0.600901,0.113401,0.136974,0.827903,0.546755
KO,0.507952,0.309668,0.687838,-0.051484,1.085734,9,0.507942,0.492058,0.188543,0.177590,1.061673,0.507005
LNT,0.865457,0.355652,0.506648,0.126184,0.971491,9,0.565086,0.434914,0.152972,0.171287,0.893072,0.411004
MCD,0.314079,0.123567,0.540851,-0.210976,1.068325,9,0.367169,0.632831,0.137549,0.136895,1.004777,0.634341
MDLZ,0.808367,0.326994,0.100409,0.401756,0.868746,9,0.501254,0.498746,0.202339,0.143150,1.413476,0.592957
MKC,0.518681,0.591668,0.418703,-0.021205,0.907670,9,0.483103,0.516897,0.056560,0.160509,0.352381,0.306838
MKTX,0.399881,0.214649,0.985512,-0.471938,0.524022,9,0.330425,0.669575,0.193696,0.297498,0.651083,0.540278
NEE,0.491760,0.394598,0.214891,-0.027690,0.994062,9,0.413524,0.586476,0.251772,0.204829,1.229183,0.650217
NEM,0.233639,-0.467379,0.920061,-0.725163,0.282156,9,0.048663,0.951337,0.301535,0.271811,1.109354,1.002004
NI,0.998797,-0.008673,0.279552,-0.056571,0.904967,9,0.423614,0.576386,0.181579,0.176617,1.028093,0.584426
O,0.964225,0.583043,0.451379,-0.362587,1.347101,5,0.596632,0.403368,0.286787,0.184057,1.558144,0.503506
ORLY,-0.297526,-0.249819,0.297465,0.243959,0.992495,9,0.197315,0.802685,0.241289,0.212911,1.133287,0.854506
PEG,0.640054,0.023724,0.294489,0.171683,1.093031,9,0.444596,0.555404,0.175929,0.161395,1.090056,0.579873
PEP,0.793869,0.423638,0.661784,0.031393,0.807842,9,0.543705,0.456295,0.171435,0.155324,1.103723,0.479375
PNW,0.763766,0.246101,0.085306,-0.435912,1.128328,9,0.357518,0.642482,0.256775,0.223141,1.150733,0.689205
PPL,0.720678,-0.020615,0.135247,0.281188,1.374079,9,0.498115,0.501885,0.203045,0.173907,1.167551,0.542303
SBAC,0.615326,0.717906,0.153646,-0.118575,0.757587,9,0.425178,0.574822,0.177779,0.198105,0.897397,0.544535
SJM,0.672289,0.567134,0.043394,0.398177,0.398536,9,0.415906,0.584094,0.016898,0.184327,0.091673,0.176850
SO,0.653423,-0.265818,0.061754,-0.095444,1.097114,9,0.290206,0.709794,0.148280,0.137456,1.078739,0.737209
SRE,0.683623,0.206838,0.446883,0.328070,1.213348,9,0.575752,0.424248,1.090047,0.194903,5.592761,1.003304
VZ,0.324329,0.060847,0.802959,0.062562,0.402950,9,0.330730,0.669270,0.272776,0.126790,2.151405,0.981664
WEC,0.375244,0.064560,0.053054,-0.106203,0.912834,9,0.259898,0.740102,0.096595,0.172251,0.560779,0.554227
WM,0.731543,0.665585,-0.107269,0.313536,0.875331,9,0.495745,0.504255,0.196548,0.152910,1.285383,0.571698
XEL,0.468746,-0.003058,0.100311,-0.161306,0.857456,9,0.252430,0.747570,0.131478,0.158211,0.831026,0.681490

In [ ]:
cov = pd.DataFrame(np.cov(np.exp(one_year_weekly_return)-1,rowvar=False,bias = False)*51,index= one_year_weekly_return.columns, columns= one_year_weekly_return.columns)
E_2 = Rfwd_adjusted/fall
E_3 = Rfwd_adjusted/PEG
E_4 = Rfwd_adjusted
std =  np.std(np.exp(one_year_weekly_return)-1)*np.sqrt(52)

# Optimization

In [ ]:
w0 = 1/selected_stock_number*np.ones(selected_stock_number)
uplim_ini = np.zeros(selected_stock_number)
uplim3 =pd.DataFrame( w1*(1-uplim_ini) + w2 * uplim_ini,index = std.index,columns=["weight"])
for i in uplim3.index:
    if i in ["SPY","IWD"]:
        uplim3.loc[i,:]=0
low_lim =  np.zeros(selected_stock_number)
multi=lambda x: x.T @cov@x

In [ ]:
ef = EfficientFrontier(E_2/100, cov,weight_bounds=(0, w1))
#ef.add_constraint(lambda w: w@E_2== 12)
raw_weights = ef.max_sharpe(0.01)
cleaned_weights = ef.clean_weights()
print(cleaned_weights)
ef.portfolio_performance(verbose=True)

OrderedDict([('AAP', 0.0), ('AEE', 0.0), ('AEP', 0.0), ('AMT', 0.0), ('ATO', 0.0), ('AWK', 0.0), ('AZO', 0.05), ('CCI', 0.0), ('CHD', 0.05), ('CLX', 0.0), ('CMS', 0.0), ('CNP', 0.0), ('CPB', 0.0), ('D', 0.0), ('DLTR', 0.0), ('DTE', 0.05), ('DUK', 0.05), ('ED', 0.0), ('ES', 0.0), ('ETR', 0.0), ('EVRG', 0.05), ('EXC', 0.05), ('FE', 0.0), ('HRL', 0.0), ('HSY', 0.04084), ('ICE', 0.05), ('KMB', 0.00916), ('KO', 0.0), ('LNT', 0.0), ('MCD', 0.05), ('MDLZ', 0.05), ('MKC', 0.0), ('MKTX', 0.0), ('NEE', 0.05), ('NEM', 0.0), ('NI', 0.05), ('O', 0.05), ('ORLY', 0.05), ('PEG', 0.05), ('PEP', 0.0), ('PNW', 0.0), ('PPL', 0.05), ('SBAC', 0.0), ('SJM', 0.0), ('SO', 0.05), ('SRE', 0.05), ('VZ', 0.05), ('WEC', 0.0), ('WM', 0.05), ('XEL', 0.0)])
Expected annual return: 2.6%
Annual volatility: 10.9%
Sharpe Ratio: 0.14

/usr/local/lib/python3.10/dist-packages/pypfopt/efficient_frontier/efficient_frontier.py:441: UserWarning: The risk_free_rate provided to portfolio_performance is different to the one used by max_sharpe. Using the previous value.
  warnings.warn(

(0.025748056141200692, 0.10884666394021796, 0.14468110983952642)

In [ ]:
weight1=np.array(pd.DataFrame(cleaned_weights.values(), index = list(cleaned_weights),columns = ["weight"]))[:,0]

In [ ]:
sd1 = np.sqrt(weight1@cov@weight1.T)
R1 = weight1.T@E_2/100
sharpe_ratio1 = (R1-0.01)/sd1
print("new_sharpe:",sharpe_ratio1)

new_sharpe: 0.14468110983927085

weight2 =   pd.read_excel("old_weight.xlsx",index_col=0)
weight2=np.array(weight2.loc[list(cleaned_weights),:])[:,0]

sd2 = np.sqrt(weight2@cov@weight2.T)
R2 = weight2.T@E_2/100
sharpe_ratio2 = (R2-0.01)/sd2
print("old_sharpe:",sharpe_ratio2)

In [ ]:
weight=pd.DataFrame(cleaned_weights.values(), index = list(cleaned_weights),columns = ["weight"])
weight = weight[weight.weight >=0.01]
weight.weight = weight.weight/sum(weight.weight)
weight.to_csv("weights.csv")

See pyportfolioopt.readthedocs.io/en/latest/MeanVariance.html for more reference

In [ ]:
if stock_type == "S&P100":
    OEX=pdr.get_data_yahoo("^OEX", start=start_swan_date, end=end_swan_date)["Adj Close"]

elif stock_type == "S&P500":
    OEX=pdr.get_data_yahoo("SPY", start=start_swan_date, end=end_swan_date)["Adj Close"]

stock_price=pdr.get_data_yahoo(list(weight.index), start=start_swan_date, end=end_swan_date)["Adj Close"]

[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  20 of 20 completed

In [ ]:
stock_price.to_csv("tradeinfo.csv")
stock_price

Ticker,AZO,CHD,DTE,DUK,EVRG,EXC,HSY,ICE,MCD,MDLZ,NEE,NI,O,ORLY,PEG,PPL,SO,SRE,VZ,WM
Date,,,,,,,,,,,,,,,,,,,,
2022-01-03,2045.109985,98.757210,109.680992,93.379715,61.367886,37.294476,183.493134,129.189636,253.779907,62.195683,85.932907,25.153751,62.734241,695.940002,60.583618,27.614265,61.774128,60.977718,44.100864,156.225571
2022-01-04,2080.250000,98.864006,109.865051,93.307533,61.205830,37.255264,185.060120,129.305389,253.713745,62.648220,85.014137,25.245153,63.659382,698.859985,60.427948,27.476837,61.774128,62.077248,44.967079,157.723114
2022-01-05,2034.030029,99.563110,109.745415,93.515068,60.782669,37.229122,187.092529,127.685066,252.466492,63.553307,84.123489,25.382257,62.628521,685.330017,60.281437,27.531809,61.846619,62.456078,45.429619,155.361572
2022-01-06,2062.489990,99.728172,110.039909,93.361664,60.548557,37.072292,186.684128,128.427734,254.828705,63.525017,80.410912,25.272573,62.919270,700.219971,60.336384,27.495159,61.774128,62.904209,45.210957,156.331146
2022-01-07,2014.770020,100.592346,110.150352,94.291054,60.818680,37.013477,186.000351,128.514511,252.343613,63.685291,81.010933,25.473656,62.919270,682.250000,61.352825,27.715048,62.200027,63.851284,46.164200,155.284775
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-12-23,2430.649902,80.633987,112.328308,96.570061,59.133858,40.695072,228.077362,100.578888,258.487976,64.403381,80.594124,26.183197,59.100235,833.549988,57.814514,27.940247,67.578255,75.044014,34.070160,155.292267
2022-12-27,2454.320068,80.486603,112.982147,97.207680,59.264565,40.799080,227.932297,99.894104,257.782715,64.777710,80.431358,26.268238,58.824970,843.840027,58.505489,28.082123,68.077515,75.562538,34.815250,155.575089
2022-12-28,2461.629883,79.513794,112.025078,96.485680,59.031166,40.600517,225.166901,100.050629,256.111420,64.144241,79.627045,26.032009,58.017506,844.619995,58.013283,27.845661,67.493484,74.363739,34.424969,153.497528
2022-12-29,2464.379883,80.162338,112.934761,97.367081,59.301907,40.780167,225.534348,101.840912,256.903625,64.651047,80.507965,26.306032,58.751549,843.659973,58.524422,28.053747,68.002159,74.154411,34.824116,154.960602
2022-12-30,2466.179932,79.209198,111.371231,96.570061,58.751091,40.874722,223.909943,100.363670,254.585068,64.342140,80.048347,25.909174,58.428234,844.030029,57.994354,27.637573,67.267410,73.516968,34.948303,153.019577

In [ ]:
start=stock_price.loc["2022-01-03"]
end = stock_price.loc["2022-10-12"]
stock_drop=abs(end/start-1)
market_drop = abs(OEX.loc["2022-10-12"]/OEX.loc["2022-01-03"]-1)

In [ ]:
beta = stock_drop/market_drop
1-beta.T@weight

weight    0.392978
dtype: float64

In [ ]:
stock_drop

Ticker
AZO     0.098225
CHD     0.287328
DTE     0.117157
DUK     0.145598
EVRG    0.170252
EXC     0.096194
HSY     0.177673
ICE     0.316300
MCD     0.102644
MDLZ    0.122992
NEE     0.193472
NI      0.099720
O       0.165241
ORLY    0.045435
PEG     0.171973
PPL     0.185014
SO      0.072015
SRE     0.089635
VZ      0.282358
WM      0.040052
dtype: float64

In [ ]:
print(len(weight))
weight

20

        weight
AZO   0.050462
CHD   0.050462
DTE   0.050462
DUK   0.050462
EVRG  0.050462
EXC   0.050462
HSY   0.041218
ICE   0.050462
MCD   0.050462
MDLZ  0.050462
NEE   0.050462
NI    0.050462
O     0.050462
ORLY  0.050462
PEG   0.050462
PPL   0.050462
SO    0.050462
SRE   0.050462
VZ    0.050462
WM    0.050462

In [ ]:
rest=1
extra=0
for i, row in weight.iterrows():
  if row['weight']>0.17:
    rest=rest-row['weight']
    extra=extra+(row['weight']-0.17)
    #row['weight']=0.17

for i,row in weight.iterrows():
  if row['weight']<0.165:
    #row['weight']=row['weight']+row['weight']/rest*extra
    a=1

weight.to_csv("weights.csv")
weight

        weight
AZO   0.050462
CHD   0.050462
DTE   0.050462
DUK   0.050462
EVRG  0.050462
EXC   0.050462
HSY   0.041218
ICE   0.050462
MCD   0.050462
MDLZ  0.050462
NEE   0.050462
NI    0.050462
O     0.050462
ORLY  0.050462
PEG   0.050462
PPL   0.050462
SO    0.050462
SRE   0.050462
VZ    0.050462
WM    0.050462

In [ ]:
a=stock_price@weight
b=1-a.loc["2022-10-12"]/a.loc["2022-01-03"]
1-b/market_drop

weight    1.050055
dtype: float64

In [ ]:
injected_result = pd.DataFrame(index = stock_price.index)
S1 = np.array(10000*weight.T)/np.array(stock_price.iloc[0,:]).T

In [ ]:
portfolio_value = np.sum(np.array(weight.T) * stock_price,axis=1)
S1 = np.array(10000*weight.T)/np.array(stock_price.iloc[0,:]).T
injected_result["portfolio_value"]=stock_price@S1.T
S2 = 10000/float(OEX[0])
injected_result["oex"]=S2*OEX
injected_result.to_csv("Injected_result.csv")

In [ ]:
temp=injected_result.loc[["2022-01-03","2022-10-12"]]
Portfolio_DD=abs(temp['portfolio_value'][1]/temp['portfolio_value'][0]-1)
DD=abs(temp['oex'][1]/temp['oex'][0]-1)
PR=1-(Portfolio_DD/DD)
print(PR)
temp

0.5488854142960404

            portfolio_value           oex
Date
2022-01-03     10000.000000  10000.000000
2022-10-12      8894.931951   7550.360631

In [ ]:
allocation=pd.read_excel('allocation weight.xlsx',index_col='stock selected')
dfMVOstock=deepcopy(weight)
dfMVOstock['PR_SR']=''
dfMVOstock['SR']=''
for i in range(len(weight)):
    dfMVOstock.iloc[i,1]=preselected_stock.loc[weight.index[i],'PR_SR']
    dfMVOstock.iloc[i,2]=preselected_stock.loc[weight.index[i],'SR']
dfMVOstock_sort=dfMVOstock.sort_values(by='PR_SR',ascending=False)
postallocationweight=post_allocation(dfMVOstock_sort)
postallocationweight

,weight,PR_SR,SR,equal,proportion,adjusted proportion,direct
AZO,0.050462,1.261022,1.389165,0.05,0.08905,0.06,0.06
SRE,0.050462,1.003304,5.592761,0.05,0.070851,0.06,0.06
VZ,0.050462,0.981664,2.151405,0.05,0.069322,0.06,0.06
ORLY,0.050462,0.854506,1.133287,0.05,0.060343,0.06,0.06
CHD,0.050462,0.822686,1.057825,0.05,0.058096,0.06,0.06
DUK,0.050462,0.787586,1.215082,0.05,0.055617,0.058795,0.06
EXC,0.050462,0.741579,2.710706,0.05,0.052368,0.055546,0.06
SO,0.050462,0.737209,1.078739,0.05,0.05206,0.055237,0.06
EVRG,0.050462,0.678598,1.226239,0.05,0.047921,0.051098,0.06
NEE,0.050462,0.650217,1.229183,0.05,0.045917,0.049094,0.06
MCD,0.050462,0.634341,1.004777,0.05,0.044795,0.047973,0.06
MDLZ,0.050462,0.592957,1.413476,0.05,0.041873,0.045051,0.037778
DTE,0.050462,0.585003,1.416973,0.05,0.041311,0.044489,0.037778
NI,0.050462,0.584426,1.028093,0.05,0.041271,0.044448,0.037778
PEG,0.050462,0.579873,1.090056,0.05,0.040949,0.044127,0.037778
WM,0.050462,0.571698,1.285383,0.05,0.040372,0.043549,0.037778
PPL,0.050462,0.542303,1.167551,0.05,0.038296,0.041473,0.037778
HSY,0.041218,0.525198,0.703241,0.05,0.037088,0.040266,0.037778
ICE,0.050462,0.523154,1.013957,0.05,0.036944,0.040121,0.037778
O,0.050462,0.503506,1.558144,0.05,0.035556,0.038734,0.037778

In [ ]:
#draw type E graph for postallocation
MVOweight=postallocationweight['weight']
equalweight=postallocationweight['equal']
proportionweight=postallocationweight['adjusted proportion']
directweight=postallocationweight['direct']
output(MVOweight).to_csv('no_post_allocation_result.csv')
output(equalweight).to_csv('equal_weight_result.csv')
output(proportionweight).to_csv('proportional_weight_result.csv')
output(directweight).to_csv('direct_weight_result.csv')

[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  20 of 20 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  20 of 20 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  20 of 20 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  20 of 20 completed

#